### ISSUE TITLE
How to change the default "fall back" icon for any mp3 files

### ISSUE THREAD

**Issue by asmwarrior** [iZakirSheikh/Audiofy#67]
Hi, when I try to use this software in my android, I see the icons are "fall back" icons with a man raises both hands.

I'm not sure whether it is by design. But could it be possible to change the default icon? For example, I need an icon which is more simple and compact.

Anyway, this music player is very nice, thanks!

**Comment by iZakirSheikh** [comment]
> Hi, when I try to use this software in my android, I see the icons are "fall back" icons with a man raises both hands.
> 
> I'm not sure whether it is by design. But could it be possible to change the default icon? For example, I need an icon which is more simple and compact.
> 
> Anyway, this music player is very nice, thanks!

Thanks. 
Would you please post the screenshot of problem you are facing?

**Comment by asmwarrior** [comment]
Look at the below screen shot. You can see if the mp3 file does not have an icon, the default fall back icon is used.

![image](https://github.com/iZakirSheikh/Audiofy/assets/561818/fcc3400c-0f26-4526-a345-08eab559e5af)

**Comment by iZakirSheikh** [comment]
In the next version this will be fixed.
Thany for the report.

**Comment by asmwarrior** [comment]
OK, thanks.

**Comment by iZakirSheikh** [comment]
#70 fixes this issue.

**Comment by asmwarrior** [comment]
Thanks.
Is there any nightly build version of apk file? So that I can try it on my phone.
