### ISSUE TITLE
start Playback

### ISSUE THREAD

**Issue by valiantyan** [iZakirSheikh/Audiofy#69]
Why can't I see how to start the Playback service?

**Comment by iZakirSheikh** [comment]
I can't understand you. What are you refering to.

**Comment by valiantyan** [comment]
Why is there no startService Playback code? I didn't understand how to startService when I looked at the code.

**Comment by iZakirSheikh** [comment]
Actually 

> Why is there no startService Playback code? I didn't understand how to startService when I looked at the code.

Oh I see.
Actually it is automatically handled by Android media3 library.
When you call play on Remote (see RemoteImpl); the library start is automatically handled.

**Comment by valiantyan** [comment]
I found that after playing the wrong music file, the playback service can no longer work properly

Uploading error.mp4…

**Comment by valiantyan** [comment]
https://github.com/iZakirSheikh/Audiofy/assets/5484163/787f2afb-4fcf-4b16-89b5-b190349f85dc

**Comment by iZakirSheikh** [comment]
* So, after playing this error file. Does this make the app not play new file.
* Also,is it be possible for you to include the file which is causing the error.
* What device and os version are u using to play the file.
* Is the app  (audiofy ) from play store or GitHub.

**Comment by valiantyan** [comment]
- There is an error file resource in the playlist
- oppo A58 Android 12
- from github master branch

**Comment by valiantyan** [comment]
error file [
[file.zip](https://github.com/user-attachments/files/15781240/file.zip)
](url)

**Comment by valiantyan** [comment]
![image](https://github.com/iZakirSheikh/Audiofy/assets/5484163/1154734b-cc43-40e8-aefd-5ca1ffe4a037)
 Add player.prepare() and it will be normal
