### ISSUE TITLE
Persistent delete permission

### ISSUE THREAD

**Issue by sercell** [iZakirSheikh/Audiofy#72]
HI.
when i want delete a track, Audiofy always asks for permission, not only the first time. I don't trash files.
Android 13.
thx

**Comment by iZakirSheikh** [comment]
Since Android 10, deleting files requires confirmation to ensure security. This is a normal behavior and can't be disabled.

**Comment by iZakirSheikh** [comment]
Since Android 10, deleting files requires confirmation to ensure security. This is a normal behavior and can't be disabled.
