### ISSUE TITLE
Crash of the tag editor with flac files

### ISSUE THREAD

**Issue by sercell** [iZakirSheikh/Audiofy#82]
Hi.
When using the editor with a flac file the app crashes. I dont know if this happens only with flac files or with every file different from an .mp3 file.

**Comment by iZakirSheikh** [comment]
Thanks for the report. Currently tag editor only supports mp3. I have plans to an advanced editor  that supports more files like flac.
BTW, Thanks for the report

**Comment by iZakirSheikh** [comment]
> Hy iZakir. Thx for the replay. Perhaps it would be useful a message that avoids editing files that are not mp3, since actually the app crasches. thx, by.

My bad I didn't think of it at that time. Sorry for the in convince it has caused you. 
I am working on 3.0.0 release that will hopefully clear all these issues once and for all. 
Please keep supporting me.

Sincerely Audiofy

**Comment by iZakirSheikh** [comment]
Fixed the issue with latest update. It now shows error when called on files other than Mp3.
Thanks for the report.

**Comment by iZakirSheikh** [comment]
> Hi. When using the editor with a flac file the app crashes. I dont know if this happens only with flac files or with every file different from an .mp3 file.

Fixed the issue with latest update. It now shows error when called on files other than Mp3.
Thanks for the report.
